
package uy.mgcoders.wsclient.stock;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioRecepcionStock", targetNamespace = "http://services.mgcoders.uy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioRecepcionStock {


    /**
     * 
     * @param idReserva
     * @return
     *     returns uy.mgcoders.wsclient.stock.ResultadoAnulacion
     */
    @WebMethod
    @WebResult(partName = "return")
    public ResultadoAnulacion anularReserva(
        @WebParam(name = "idReserva", partName = "idReserva")
        long idReserva);

    /**
     * 
     * @param productos
     * @return
     *     returns uy.mgcoders.wsclient.stock.Resultado
     */
    @WebMethod
    @WebResult(partName = "return")
    public Resultado reservarProducto(
        @WebParam(name = "productos", partName = "productos")
        Reserva productos);

}
