
package uy.mgcoders.wsclient.epuerto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioEPuerto", targetNamespace = "http://services.mgcoders.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioEPuerto {


    /**
     * 
     * @param identificadorReserva
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "anularOrden", targetNamespace = "http://services.mgcoders.uy/", className = "uy.mgcoders.wsclient.epuerto.AnularOrden")
    @ResponseWrapper(localName = "anularOrdenResponse", targetNamespace = "http://services.mgcoders.uy/", className = "uy.mgcoders.wsclient.epuerto.AnularOrdenResponse")
    public String anularOrden(
        @WebParam(name = "identificadorReserva", targetNamespace = "")
        String identificadorReserva);

    /**
     * 
     * @param identificadorProducto
     * @param identificadorCompra
     * @param cantidad
     * @return
     *     returns uy.mgcoders.wsclient.epuerto.ConfirmacionOrden
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "colocarOrden", targetNamespace = "http://services.mgcoders.uy/", className = "uy.mgcoders.wsclient.epuerto.ColocarOrden")
    @ResponseWrapper(localName = "colocarOrdenResponse", targetNamespace = "http://services.mgcoders.uy/", className = "uy.mgcoders.wsclient.epuerto.ColocarOrdenResponse")
    public ConfirmacionOrden colocarOrden(
        @WebParam(name = "identificadorCompra", targetNamespace = "")
        String identificadorCompra,
        @WebParam(name = "identificadorProducto", targetNamespace = "")
        long identificadorProducto,
        @WebParam(name = "cantidad", targetNamespace = "")
        int cantidad);

}
