
package uy.mgcoders.wsclient.epuerto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioEPuerto", targetNamespace = "http://services.mgcoders.uy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioEPuerto {


    /**
     * 
     * @param identificadorReserva
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String anularOrden(
        @WebParam(name = "identificadorReserva", partName = "identificadorReserva")
        String identificadorReserva);

    /**
     * 
     * @param orden
     * @return
     *     returns uy.mgcoders.wsclient.epuerto.ConfirmacionOrden
     */
    @WebMethod
    @WebResult(partName = "return")
    public ConfirmacionOrden colocarOrden(
        @WebParam(name = "orden", partName = "orden")
        OrdenEpuerto orden);

}
