package org.fing.middleware.services;

import uy.mgcoders.listener.IProcesarPagos;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.213-03:00
 * Generated source version: 3.1.2
 *
 wsdlLocation = "file:../resources/payment-service.wsdl",
 */

@javax.jws.WebService(
                      serviceName = "ServicioRecepcionPagosService",
                      portName = "ServicioRecepcionPagosPort",
                      targetNamespace = "http://services.middleware.fing.org/",
                      endpointInterface = "org.fing.middleware.services.ServicioRecepcionPagos")

public class ServicioRecepcionPagosPortImpl implements ServicioRecepcionPagos {

    private static final Logger LOG = Logger.getLogger(ServicioRecepcionPagosPortImpl.class.getName());

    IProcesarPagos iProcesarPagos;

    public ConfirmacionTransaccion recepcionPagos(TransaccionPago arg0) {

        LOG.info("Executing operation recepcionPagos");
        System.out.println(arg0);

        try {
            ConfirmacionTransaccion resultado = new ConfirmacionTransaccion();
            resultado.confirmacion = iProcesarPagos.procesarPagos(arg0);
            return resultado;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public IProcesarPagos getiProcesarPagos() {
        return iProcesarPagos;
    }

    public void setiProcesarPagos(IProcesarPagos iProcesarPagos) {
        this.iProcesarPagos = iProcesarPagos;
    }
}
