package org.fing.middleware.services;

import org.fing.middleware.integration.RecepcionPagosGateway;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.integration.support.MessageBuilder;
import org.springframework.messaging.Message;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.213-03:00
 * Generated source version: 3.1.2
 *
 wsdlLocation = "file:../resources/payment-service.wsdl",
 */

@javax.jws.WebService(
                      serviceName = "ServicioRecepcionPagosService",
                      portName = "ServicioRecepcionPagosPort",
                      targetNamespace = "http://services.middleware.fing.org/",
                      endpointInterface = "org.fing.middleware.services.ServicioRecepcionPagos")

public class ServicioRecepcionPagosPortImpl implements ServicioRecepcionPagos {

    private static final Logger LOG = Logger.getLogger(ServicioRecepcionPagosPortImpl.class.getName());

    @Autowired
    ApplicationContext applicationContext;

    public ConfirmacionTransaccion recepcionPagos(TransaccionPago arg0) {

        RecepcionPagosGateway broker = applicationContext.getBean("recepcionPagosGateway", RecepcionPagosGateway.class);

        ConfirmacionTransaccion resultado = new ConfirmacionTransaccion();

        Message<TransaccionPago> mensaje = MessageBuilder.withPayload(arg0)
                .setSequenceSize(arg0.getPagos().size())
                .setCorrelationId(arg0.getIdentificadorCliente())
                .build();

        resultado.confirmacion = broker.procesarPagos(mensaje);

        return  resultado;
    }
}
