
package org.fing.middleware.services;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.233-03:00
 * Generated source version: 3.1.2
 * 
 */
 
public class ServicioRecepcionPagos_ServicioRecepcionPagosPort_Server{

    protected ServicioRecepcionPagos_ServicioRecepcionPagosPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ServicioRecepcionPagosPortImpl();
        String address = "http://localhost:8080/ws-facturas/otherservices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ServicioRecepcionPagos_ServicioRecepcionPagosPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
