
package org.fing.middleware.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.176-03:00
 * Generated source version: 3.1.2
 * 
 */
public final class ServicioRecepcionPagos_ServicioRecepcionPagosPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.middleware.fing.org/", "ServicioRecepcionPagosService");

    private ServicioRecepcionPagos_ServicioRecepcionPagosPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicioRecepcionPagosService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServicioRecepcionPagosService ss = new ServicioRecepcionPagosService(wsdlURL, SERVICE_NAME);
        ServicioRecepcionPagos port = ss.getServicioRecepcionPagosPort();  
        
        {
        System.out.println("Invoking recepcionPagos...");
        org.fing.middleware.services.TransaccionPago _recepcionPagos_arg0 = null;
        org.fing.middleware.services.ConfirmacionTransaccion _recepcionPagos__return = port.recepcionPagos(_recepcionPagos_arg0);
        System.out.println("recepcionPagos.result=" + _recepcionPagos__return);


        }

        System.exit(0);
    }

}
