package org.fing.middleware.services;

import org.fing.middleware.integration.RecepcionPagosGateway;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.213-03:00
 * Generated source version: 3.1.2
 *
 wsdlLocation = "file:../resources/payment-service.wsdl",
 */

@javax.jws.WebService(
                      serviceName = "ServicioRecepcionPagosService",
                      portName = "ServicioRecepcionPagosPort",
                      targetNamespace = "http://services.middleware.fing.org/",
                      endpointInterface = "org.fing.middleware.services.ServicioRecepcionPagos")

public class ServicioRecepcionPagosPortImpl implements ServicioRecepcionPagos {

    private static final Logger LOG = Logger.getLogger(ServicioRecepcionPagosPortImpl.class.getName());

    public ConfirmacionTransaccion recepcionPagos(TransaccionPago arg0) {
        LOG.info("Executing operation recepcionPagos");
        ApplicationContext context =  new ClassPathXmlApplicationContext("META-INF/spring-integration-config.xml");
        RecepcionPagosGateway broker = context.getBean("recepcionPagosGateway", RecepcionPagosGateway.class);

        ConfirmacionTransaccion resultado = new ConfirmacionTransaccion();
        resultado.confirmacion = broker.procesarPagos(arg0);

        return  resultado;
    }

}
