package org.fing.middleware.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.236-03:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "ServicioRecepcionPagosService", 
                  wsdlLocation = "file:../resources/payment-service.wsdl",
                  targetNamespace = "http://services.middleware.fing.org/") 
public class ServicioRecepcionPagosService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.middleware.fing.org/", "ServicioRecepcionPagosService");
    public final static QName ServicioRecepcionPagosPort = new QName("http://services.middleware.fing.org/", "ServicioRecepcionPagosPort");
    static {
        URL url = null;
        try {
            url = new URL("file:../resources/payment-service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioRecepcionPagosService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:../resources/payment-service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioRecepcionPagosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioRecepcionPagosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioRecepcionPagosService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServicioRecepcionPagosService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioRecepcionPagosService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioRecepcionPagosService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ServicioRecepcionPagos
     */
    @WebEndpoint(name = "ServicioRecepcionPagosPort")
    public ServicioRecepcionPagos getServicioRecepcionPagosPort() {
        return super.getPort(ServicioRecepcionPagosPort, ServicioRecepcionPagos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioRecepcionPagos
     */
    @WebEndpoint(name = "ServicioRecepcionPagosPort")
    public ServicioRecepcionPagos getServicioRecepcionPagosPort(WebServiceFeature... features) {
        return super.getPort(ServicioRecepcionPagosPort, ServicioRecepcionPagos.class, features);
    }

}
