package org.fing.middleware.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T17:24:47.228-03:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://services.middleware.fing.org/", name = "ServicioRecepcionPagos")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicioRecepcionPagos {

    @WebMethod
    @Action(input = "http://services.middleware.fing.org/ServicioRecepcionPagos/recepcionPagosRequest", output = "http://services.middleware.fing.org/ServicioRecepcionPagos/recepcionPagosResponse")
    @RequestWrapper(localName = "recepcionPagos", targetNamespace = "http://services.middleware.fing.org/", className = "org.fing.middleware.services.RecepcionPagos")
    @ResponseWrapper(localName = "recepcionPagosResponse", targetNamespace = "http://services.middleware.fing.org/", className = "org.fing.middleware.services.RecepcionPagosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.fing.middleware.services.ConfirmacionTransaccion recepcionPagos(
        @WebParam(name = "arg0", targetNamespace = "")
        org.fing.middleware.services.TransaccionPago arg0
    );
}
