
package uy.mgcoders.wsclient.pubsub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnularViaPS", targetNamespace = "http://services.mgcoders.uy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AnularViaPS {


    /**
     * 
     * @param servicio
     * @param idReserva
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String anularReservas(
        @WebParam(name = "idReserva", partName = "idReserva")
        long idReserva,
        @WebParam(name = "servicio", partName = "servicio")
        String servicio);

}
