
package uy.mgcoders.wsclient.pubsub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnularViaPSService", targetNamespace = "http://services.mgcoders.uy/", wsdlLocation = "http://localhost:8181/esb/pubsub?wsdl")
public class AnularViaPSService
    extends Service
{

    private final static URL ANULARVIAPSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANULARVIAPSSERVICE_EXCEPTION;
    private final static QName ANULARVIAPSSERVICE_QNAME = new QName("http://services.mgcoders.uy/", "AnularViaPSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8181/esb/pubsub?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANULARVIAPSSERVICE_WSDL_LOCATION = url;
        ANULARVIAPSSERVICE_EXCEPTION = e;
    }

    public AnularViaPSService() {
        super(__getWsdlLocation(), ANULARVIAPSSERVICE_QNAME);
    }

    public AnularViaPSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANULARVIAPSSERVICE_QNAME, features);
    }

    public AnularViaPSService(URL wsdlLocation) {
        super(wsdlLocation, ANULARVIAPSSERVICE_QNAME);
    }

    public AnularViaPSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANULARVIAPSSERVICE_QNAME, features);
    }

    public AnularViaPSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnularViaPSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnularViaPS
     */
    @WebEndpoint(name = "AnularViaPSPort")
    public AnularViaPS getAnularViaPSPort() {
        return super.getPort(new QName("http://services.mgcoders.uy/", "AnularViaPSPort"), AnularViaPS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnularViaPS
     */
    @WebEndpoint(name = "AnularViaPSPort")
    public AnularViaPS getAnularViaPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.mgcoders.uy/", "AnularViaPSPort"), AnularViaPS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANULARVIAPSSERVICE_EXCEPTION!= null) {
            throw ANULARVIAPSSERVICE_EXCEPTION;
        }
        return ANULARVIAPSSERVICE_WSDL_LOCATION;
    }

}
