<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://services.mgcoders.uy/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="AnularViaPSService" targetNamespace="http://services.mgcoders.uy/">
  <wsdl:message name="anularReservasResponse">
    <wsdl:part name="return" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="anularReservas">
    <wsdl:part name="idReserva" type="xsd:long">
    </wsdl:part>
    <wsdl:part name="servicio" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AnularViaPS">
    <wsdl:operation name="anularReservas">
      <wsdl:input message="tns:anularReservas" name="anularReservas">
    </wsdl:input>
      <wsdl:output message="tns:anularReservasResponse" name="anularReservasResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AnularViaPSServiceSoapBinding" type="tns:AnularViaPS">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="anularReservas">
      <soap:operation soapAction="" style="rpc"/>
      <wsdl:input name="anularReservas">
        <soap:body namespace="http://services.mgcoders.uy/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="anularReservasResponse">
        <soap:body namespace="http://services.mgcoders.uy/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AnularViaPSService">
    <wsdl:port binding="tns:AnularViaPSServiceSoapBinding" name="AnularViaPSPort">
      <soap:address location="http://localhost:8181/esb/pubsub"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>