
package uy.mgcoders.wsclient.pagosya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioRecepcionPagos", targetNamespace = "http://services.mgcoders.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioRecepcionPagos {


    /**
     * 
     * @param fecha
     * @param monto
     * @param idCompra
     * @param numeroTarjeta
     * @return
     *     returns uy.mgcoders.wsclient.pagosya.ConfirmacionPago
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recepcionPago", targetNamespace = "http://services.mgcoders.uy/", className = "uy.mgcoders.wsclient.pagosya.RecepcionPago")
    @ResponseWrapper(localName = "recepcionPagoResponse", targetNamespace = "http://services.mgcoders.uy/", className = "uy.mgcoders.wsclient.pagosya.RecepcionPagoResponse")
    public ConfirmacionPago recepcionPago(
        @WebParam(name = "idCompra", targetNamespace = "")
        String idCompra,
        @WebParam(name = "numeroTarjeta", targetNamespace = "")
        String numeroTarjeta,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha);

}
