
package uy.mgcoders.callback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioCallbackService", targetNamespace = "http://services.mgcoders.uy/", wsdlLocation = "http://localhost:8080/callback/ServicioCallback?wsdl")
public class ServicioCallbackService
    extends Service
{

    private final static URL SERVICIOCALLBACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOCALLBACKSERVICE_EXCEPTION;
    private final static QName SERVICIOCALLBACKSERVICE_QNAME = new QName("http://services.mgcoders.uy/", "ServicioCallbackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/callback/ServicioCallback?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOCALLBACKSERVICE_WSDL_LOCATION = url;
        SERVICIOCALLBACKSERVICE_EXCEPTION = e;
    }

    public ServicioCallbackService() {
        super(__getWsdlLocation(), SERVICIOCALLBACKSERVICE_QNAME);
    }

    public ServicioCallbackService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOCALLBACKSERVICE_QNAME, features);
    }

    public ServicioCallbackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOCALLBACKSERVICE_QNAME);
    }

    public ServicioCallbackService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOCALLBACKSERVICE_QNAME, features);
    }

    public ServicioCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioCallbackService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioCallback
     */
    @WebEndpoint(name = "ServicioCallbackPort")
    public ServicioCallback getServicioCallbackPort() {
        return super.getPort(new QName("http://services.mgcoders.uy/", "ServicioCallbackPort"), ServicioCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioCallback
     */
    @WebEndpoint(name = "ServicioCallbackPort")
    public ServicioCallback getServicioCallbackPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.mgcoders.uy/", "ServicioCallbackPort"), ServicioCallback.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOCALLBACKSERVICE_EXCEPTION!= null) {
            throw SERVICIOCALLBACKSERVICE_EXCEPTION;
        }
        return SERVICIOCALLBACKSERVICE_WSDL_LOCATION;
    }

}
