
package uy.mgcoders.wsclient.callback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioCallback", targetNamespace = "http://services.mgcoders.uy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioCallback {


    /**
     * 
     * @param resultado
     */
    @WebMethod
    public void confirmarOrden(
        @WebParam(name = "resultado", partName = "resultado")
        Resultado resultado);

}
