
package org.fing.middleware.serviceCobroFactura;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "IServicioCobroDeFacturas", targetNamespace = "http://services.middleware.fing.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IServicioCobroDeFacturas {


    /**
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns org.fing.middleware.serviceCobroFactura.WsResult
     */
    @WebMethod
    @WebResult(partName = "return")
    WsResult cobrar(
            @WebParam(name = "arg0", partName = "arg0")
            long arg0,
            @WebParam(name = "arg1", partName = "arg1")
            short arg1,
            @WebParam(name = "arg2", partName = "arg2")
            BigDecimal arg2,
            @WebParam(name = "arg3", partName = "arg3")
            XMLGregorianCalendar arg3);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    String echo(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);

}
