
package org.fing.middleware.serviceCobroFactura;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ServicioCobroDeFacturasService", targetNamespace = "http://services.middleware.fing.org/", wsdlLocation = "http://localhost:8080/ws-1/ServicioCobroDeFactura?wsdl")
public class ServicioCobroDeFacturasService
        extends Service {

    private final static URL SERVICIOCOBRODEFACTURASSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOCOBRODEFACTURASSERVICE_EXCEPTION;
    private final static QName SERVICIOCOBRODEFACTURASSERVICE_QNAME = new QName("http://services.middleware.fing.org/", "ServicioCobroDeFacturasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws-1/ServicioCobroDeFactura?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOCOBRODEFACTURASSERVICE_WSDL_LOCATION = url;
        SERVICIOCOBRODEFACTURASSERVICE_EXCEPTION = e;
    }

    public ServicioCobroDeFacturasService() {
        super(__getWsdlLocation(), SERVICIOCOBRODEFACTURASSERVICE_QNAME);
    }

    public ServicioCobroDeFacturasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOCOBRODEFACTURASSERVICE_QNAME, features);
    }

    public ServicioCobroDeFacturasService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOCOBRODEFACTURASSERVICE_QNAME);
    }

    public ServicioCobroDeFacturasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOCOBRODEFACTURASSERVICE_QNAME, features);
    }

    public ServicioCobroDeFacturasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioCobroDeFacturasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOCOBRODEFACTURASSERVICE_EXCEPTION != null) {
            throw SERVICIOCOBRODEFACTURASSERVICE_EXCEPTION;
        }
        return SERVICIOCOBRODEFACTURASSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns IServicioCobroDeFacturas
     */
    @WebEndpoint(name = "ServicioCobroDeFacturasPort")
    public IServicioCobroDeFacturas getServicioCobroDeFacturasPort() {
        return super.getPort(new QName("http://services.middleware.fing.org/", "ServicioCobroDeFacturasPort"), IServicioCobroDeFacturas.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IServicioCobroDeFacturas
     */
    @WebEndpoint(name = "ServicioCobroDeFacturasPort")
    public IServicioCobroDeFacturas getServicioCobroDeFacturasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.middleware.fing.org/", "ServicioCobroDeFacturasPort"), IServicioCobroDeFacturas.class, features);
    }

}
