
package otherservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ServicioRecepcionPagos", targetNamespace = "http://services.middleware.fing.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ServicioRecepcionPagos {


    /**
     * @param arg0
     * @return returns otherservices.ConfirmacionTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recepcionPagos", targetNamespace = "http://services.middleware.fing.org/", className = "otherservices.RecepcionPagos")
    @ResponseWrapper(localName = "recepcionPagosResponse", targetNamespace = "http://services.middleware.fing.org/", className = "otherservices.RecepcionPagosResponse")
    @Action(input = "http://services.middleware.fing.org/ServicioRecepcionPagos/recepcionPagosRequest", output = "http://services.middleware.fing.org/ServicioRecepcionPagos/recepcionPagosResponse")
    ConfirmacionTransaccion recepcionPagos(
            @WebParam(name = "arg0", targetNamespace = "")
            TransaccionPago arg0);

}
